---
phases:
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t swagatam04/nodeserver ."
      - "docker tag swagatam04/nodeserver swagatam04/nodeserver:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push swagatam04/nodeserver:latest"
  pre_build:
    commands:
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"swagatam04\" --password=\"pAKHI08101992@\""
version: 0.1
